# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Файл'),
        ),
    ]
