# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='gallery', verbose_name='Файл')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
    ]
