# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='file',
            field=models.ImageField(default=1, upload_to='product', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
