# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
