# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20160921_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
