# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20160921_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='metatitle',
            field=models.CharField(blank=True, max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='metatitle',
            field=models.CharField(blank=True, max_length=120, verbose_name='title'),
        ),
    ]
