# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20160921_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='metatitle',
            new_name='seotitle',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='metatitle',
            new_name='seotitle',
        ),
    ]
