# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20160921_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seotitle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='products',
            name='seotitle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
