# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20160921_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.ImageField(default=1, upload_to='category', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
