# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='seodescription',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='seodescription',
        ),
    ]
